resolver: nightly-2018-05-28

packages:
  - numhask
  - numhask-prelude
  - numhask-array
  - numhask-test
  # - numhask-bench
  # - numhask-graph
  # - ../perf/perf

extra-deps:
  - dimensions-0.3.2.0
