resolver: nightly-2018-04-03

packages:
  - numhask
  - numhask-prelude
  - numhask-array
  # - numhask-bench
  # - numhask-graph
  # - ../perf/perf

extra-deps:
  - dimensions-0.3.2.0
  - singletons-2.4.1
  - protolude-0.2.2

allow-newer: true
