name: numhask
version: '0.3.0.0'
synopsis: numeric classes
description: A numeric class heirarchy.
category: mathematics
author: Tony Day
maintainer: tonyday567@gmail.com
copyright: Tony Day
license: BSD3
github: tonyday567/numhask
extra-source-files:
- stack.yaml
default-extensions:
- NegativeLiterals
- OverloadedStrings
- UnicodeSyntax
library:
  source-dirs: src
  ghc-options: -Wall
  exposed-modules:
  - NumHask.Algebra
  - NumHask.Algebra.Additive
  - NumHask.Algebra.Basis
  - NumHask.Algebra.Distribution
  - NumHask.Algebra.Ring
  - NumHask.Algebra.Field
  - NumHask.Algebra.Integral
  - NumHask.Algebra.Magma
  - NumHask.Algebra.Metric
  - NumHask.Algebra.Module
  - NumHask.Algebra.Multiplicative
  - NumHask.Algebra.Singleton
  dependencies:
  - base >=4.7 && <4.12
