resolver: nightly-2018-04-01

packages:
  - .
  - location: ../numhask
    extra-dep: true
  - location: ../numhask-prelude
    extra-dep: true

extra-deps:
  - dimensions-0.3.2.0
  - protolude-0.2.2
  - singletons-2.4.1

allow-newer: true
